# Copyright (c) 2026 Michael Smith
# SPDX-License-Identifier: Apache-2.0

"""Render a concrete ModelFoundry recipe from a ``*.template.yaml`` base +
a parameter override mapping (Story E.d).

WHY. A recipe is a *technical artifact* — a learner working an exercise should
not hand-edit raw YAML any more than a writer edits a ``.docx``'s XML. The
exercise surfaces only the few *parameters* that matter (learning rate, weight
decay, batch size, epochs) as plain Python variables; this script turns those
parameters + a fixed template into a concrete, valid recipe behind the scenes.

MECHANISM — strict deep-merge override (not placeholder substitution).
The template is itself a complete, valid recipe with every knob at its default
value, so ``modelfoundry validate <template>`` passes as-is (no ``${...}``
tokens to break YAML/MF parsing). ``params`` is a *partial* mapping mirroring
the recipe's nesting; :func:`apply_overrides` recursively overlays it onto the
template. The merge is **strict**: an override key absent from the template, or
a scalar/mapping shape mismatch, raises :class:`RenderError`. That is the
param-surfacing contract — you may override only knobs the template already
declares, so a typo fails loud instead of silently injecting an unknown key MF
would later reject.

Upstream feature spec + migration path to a LearningFoundry capability:
``docs/specs/learningfoundry/recipe-template-spec.md``.

Usage::

    # render with template defaults (no overrides)
    python scripts/render_recipe.py models/resnet20.template.yaml --out /tmp/r.yaml

    # override surfaced knobs (each VALUE is parsed as a YAML scalar)
    python scripts/render_recipe.py models/resnet20.template.yaml \\
        --set Optimizer.learning_rate=0.002 --set Training.batch_size=96 --out /tmp/r.yaml

    # override from a nested YAML/JSON params file
    python scripts/render_recipe.py models/resnet20.template.yaml \\
        --params params.yaml --out /tmp/r.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml


class RenderError(ValueError):
    """A params mapping does not conform to the template's declared knobs."""


def apply_overrides(base: dict, overrides: dict, _path: str = "") -> dict:
    """Strict recursive deep-merge. Return a new dict; do not mutate ``base``.

    Every key in ``overrides`` must exist in ``base`` at the same nesting, and a
    leaf may not change between scalar and mapping. Violations raise
    :class:`RenderError`. Key order follows the template (so the rendered YAML
    preserves the template's layout).
    """
    if not isinstance(overrides, dict):
        raise RenderError(
            f"override at {_path or '<root>'!r} must be a mapping, "
            f"got {type(overrides).__name__}"
        )
    result = dict(base)
    for key, ov in overrides.items():
        path = f"{_path}.{key}" if _path else str(key)
        if key not in base:
            raise RenderError(f"override targets unknown key {path!r} (not declared in template)")
        bv = base[key]
        b_map, o_map = isinstance(bv, dict), isinstance(ov, dict)
        if b_map != o_map:
            want = "mapping" if b_map else "scalar"
            got = "mapping" if o_map else "scalar"
            raise RenderError(
                f"override shape mismatch at {path!r}: template is a {want}, override is a {got}"
            )
        result[key] = apply_overrides(bv, ov, path) if b_map else ov
    return result


def render_recipe(
    template_path: str | Path,
    params: dict | None = None,
    *,
    out_path: str | Path | None = None,
) -> dict:
    """Load ``template_path``, overlay ``params``, optionally write to ``out_path``.

    Return the rendered recipe as a dict.
    """
    template = yaml.safe_load(Path(template_path).read_text())
    if not isinstance(template, dict):
        raise RenderError(f"template {str(template_path)!r} did not parse to a mapping")
    rendered = apply_overrides(template, params or {})
    if out_path is not None:
        _write_recipe(rendered, Path(out_path), Path(template_path))
    return rendered


def _write_recipe(recipe: dict, out_path: Path, template_path: Path) -> None:
    header = (
        "# Copyright (c) 2026 Michael Smith\n"
        "# SPDX-License-Identifier: Apache-2.0\n"
        f"# GENERATED by scripts/render_recipe.py from {template_path.name}"
        " — do not edit by hand.\n\n"
    )
    body = yaml.safe_dump(recipe, sort_keys=False, default_flow_style=False)
    out_path.write_text(header + body)


def _deep_union(a: dict, b: dict) -> dict:
    """Union two *override* dicts (b wins) — used only to combine ``--params``
    and ``--set`` before the single strict merge against the template."""
    out = dict(a)
    for key, val in b.items():
        if isinstance(val, dict) and isinstance(out.get(key), dict):
            out[key] = _deep_union(out[key], val)
        else:
            out[key] = val
    return out


def _set_dotted(overrides: dict, dotted: str, value: Any) -> None:
    keys = dotted.split(".")
    node = overrides
    for k in keys[:-1]:
        nxt = node.setdefault(k, {})
        if not isinstance(nxt, dict):
            raise RenderError(f"--set path {dotted!r} conflicts: {k!r} already has a scalar value")
        node = nxt
    node[keys[-1]] = value


def _parse_set(pairs: list[str]) -> dict:
    overrides: dict = {}
    for pair in pairs:
        if "=" not in pair:
            raise RenderError(f"--set expects KEY=VALUE, got {pair!r}")
        key, raw = pair.split("=", 1)
        _set_dotted(overrides, key.strip(), yaml.safe_load(raw))
    return overrides


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Render a concrete recipe from a template + params.")
    ap.add_argument("template", help="path to the *.template.yaml base recipe")
    ap.add_argument("--out", help="write the rendered recipe here (else print to stdout)")
    ap.add_argument("--params", help="nested YAML/JSON file of overrides")
    ap.add_argument(
        "--set",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help="override a dotted knob path (repeatable); VALUE parsed as a YAML scalar",
    )
    args = ap.parse_args(argv)

    try:
        overrides: dict = {}
        if args.params:
            loaded = yaml.safe_load(Path(args.params).read_text()) or {}
            if not isinstance(loaded, dict):
                raise RenderError(f"--params file {args.params!r} must be a mapping")
            overrides = loaded
        if args.set:
            overrides = _deep_union(overrides, _parse_set(args.set))  # --set wins on conflict
        rendered = render_recipe(
            args.template, overrides, out_path=(Path(args.out) if args.out else None)
        )
    except (RenderError, FileNotFoundError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if not args.out:
        sys.stdout.write(yaml.safe_dump(rendered, sort_keys=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
